import { Service, Doctor, BlogPost, FAQ, PricingTier } from '@/types';

export const mockServices: Service[] = [
  {
    id: '1',
    name: 'حجز المواعيد',
    description: 'احجز موعدك بسهولة مع أفضل الأطباء في أي وقت ومن أي مكان',
    price: 0,
    duration: 30,
    category: 'المواعيد',
    features: ['حجز فوري', 'تذكيرات ذكية', 'إعادة الجدولة'],
    isPopular: true,
    icon: 'CalendarDaysIcon',
  },
  {
    id: '2',
    name: 'استشارات فيديو',
    description: 'احصل على استشارة طبية مباشرة مع طبيبك المختص عبر الفيديو',
    price: 50,
    duration: 30,
    category: 'الاستشارات',
    features: ['جودة عالية', 'تسجيل الجلسة', 'مشاركة الشاشة'],
    isPopular: false,
    icon: 'VideoCameraIcon',
  },
  {
    id: '3',
    name: 'دردشة طبية',
    description: 'تواصل مع طبيبك عبر الدردشة للحصول على استشارات سريعة',
    price: 25,
    duration: 15,
    category: 'الاستشارات',
    features: ['رد فوري', 'مشاركة الملفات', 'تاريخ المحادثات'],
    isPopular: false,
    icon: 'ChatBubbleLeftRightIcon',
  },
  {
    id: '4',
    name: 'الملف الطبي',
    description: 'احتفظ بملفك الطبي الكامل وتاريخك المرضي في مكان آمن',
    price: 0,
    duration: 0,
    category: 'السجلات',
    features: ['تشفير آمن', 'نسخ احتياطي', 'مشاركة مع الأطباء'],
    isPopular: false,
    icon: 'DocumentTextIcon',
  },
  {
    id: '5',
    name: 'مواعيد الطوارئ',
    description: 'احجز موعد طوارئ في أي وقت للحالات العاجلة',
    price: 100,
    duration: 60,
    category: 'الطوارئ',
    features: ['استجابة سريعة', 'أطباء متاحين 24/7', 'أولوية عالية'],
    isPopular: false,
    icon: 'ClockIcon',
  },
  {
    id: '6',
    name: 'أمان البيانات',
    description: 'بياناتك الطبية محمية بأعلى معايير الأمان والخصوصية',
    price: 0,
    duration: 0,
    category: 'الأمان',
    features: ['تشفير متقدم', 'امتثال GDPR', 'مراجعة أمنية'],
    isPopular: false,
    icon: 'ShieldCheckIcon',
  },
];

// تم حذف البيانات الوهمية للأطباء - الآن يتم استخدام API


export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'نصائح للحفاظ على صحة القلب',
    excerpt: 'تعرف على أهم النصائح للحفاظ على صحة القلب والوقاية من أمراض القلب والأوعية الدموية',
    content: 'محتوى المقال الكامل...',
    author: 'د. أحمد محمد العلي',
    publishedAt: '2024-01-15',
    image: '/images/blog/blog-1.jpg',
    tags: ['صحة القلب', 'نصائح طبية', 'الوقاية'],
    readTime: 5,
    slug: 'heart-health-tips',
  },
  {
    id: '2',
    title: 'أهمية الفحوصات الدورية',
    excerpt: 'لماذا تعتبر الفحوصات الدورية مهمة للحفاظ على صحتك واكتشاف الأمراض مبكراً',
    content: 'محتوى المقال الكامل...',
    author: 'د. فاطمة السعد',
    publishedAt: '2024-01-10',
    image: '/images/blog/blog-2.jpg',
    tags: ['الفحوصات', 'الوقاية', 'الصحة العامة'],
    readTime: 7,
    slug: 'importance-regular-checkups',
  },
  {
    id: '3',
    title: 'التغذية السليمة للأطفال',
    excerpt: 'دليل شامل للتغذية السليمة للأطفال في مختلف المراحل العمرية',
    content: 'محتوى المقال الكامل...',
    author: 'د. نورا أحمد الزهراني',
    publishedAt: '2024-01-05',
    image: '/images/blog/blog-3.jpg',
    tags: ['تغذية الأطفال', 'صحة الأطفال', 'التغذية'],
    readTime: 8,
    slug: 'healthy-nutrition-children',
  },
];

export const mockFAQs: FAQ[] = [
  {
    id: '1',
    question: 'كيف يمكنني حجز موعد؟',
    answer: 'يمكنك حجز موعد بسهولة من خلال الموقع الإلكتروني أو التطبيق، فقط اختر الطبيب والوقت المناسب لك.',
    category: 'المواعيد',
  },
  {
    id: '2',
    question: 'هل يمكنني إلغاء الموعد؟',
    answer: 'نعم، يمكنك إلغاء الموعد قبل 24 ساعة من الموعد المحدد دون أي رسوم إضافية.',
    category: 'المواعيد',
  },
  {
    id: '3',
    question: 'ما هي تكلفة الاستشارة؟',
    answer: 'تختلف تكلفة الاستشارة حسب نوع الخدمة والطبيب، تتراوح من 50 ريال للاستشارة العادية إلى 300 ريال للاستشارة المتخصصة.',
    category: 'الأسعار',
  },
  {
    id: '4',
    question: 'هل بياناتي آمنة؟',
    answer: 'نعم، نحن نستخدم أعلى معايير الأمان لحماية بياناتك الطبية وفقاً للمعايير الدولية.',
    category: 'الأمان',
  },
];

export const mockPricingTiers: PricingTier[] = [
  {
    id: '1',
    name: 'الخطة الأساسية',
    price: 0,
    period: 'شهرياً',
    features: [
      'حجز مواعيد مجاني',
      'تذكيرات عبر الرسائل',
      'الملف الطبي الأساسي',
      'دعم فني',
    ],
    isPopular: false,
    description: 'مناسبة للمرضى الذين يحتاجون لخدمات أساسية',
  },
  {
    id: '2',
    name: 'الخطة المتقدمة',
    price: 99,
    period: 'شهرياً',
    features: [
      'جميع ميزات الخطة الأساسية',
      'استشارات فيديو مجانية',
      'دردشة طبية 24/7',
      'تقارير صحية مفصلة',
      'أولوية في الحجز',
    ],
    isPopular: true,
    description: 'الأكثر شعبية - مناسبة لمعظم المرضى',
  },
  {
    id: '3',
    name: 'الخطة المميزة',
    price: 199,
    period: 'شهرياً',
    features: [
      'جميع ميزات الخطة المتقدمة',
      'استشارات طوارئ مجانية',
      'طبيب شخصي مخصص',
      'فحوصات دورية مجانية',
      'خدمة VIP',
    ],
    isPopular: false,
    description: 'للأسر التي تريد رعاية صحية شاملة',
  },
];
