version: '3.9'
services:
  api:
    build: ./clinic-api
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/clinic
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    ports:
      - '3000:3000'
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
volumes:
  mongo_data:

