import { Service } from '@/types';

export const mockServices: Service[] = [
  {
    id: '1',
    name: 'حجز المواعيد',
    description: 'احجز موعدك بسهولة مع أفضل الأطباء في أي وقت ومن أي مكان',
    price: 0,
    duration: 30,
    category: 'المواعيد',
    features: ['حجز فوري', 'تذكيرات ذكية', 'إعادة الجدولة'],
    isPopular: true,
    icon: 'CalendarDaysIcon',
  },
  {
    id: '2',
    name: 'استشارات فيديو',
    description: 'احصل على استشارة طبية مباشرة مع طبيبك المختص عبر الفيديو',
    price: 50,
    duration: 30,
    category: 'الاستشارات',
    features: ['جودة عالية', 'تسجيل الجلسة', 'مشاركة الشاشة'],
    isPopular: false,
    icon: 'VideoCameraIcon',
  },
  {
    id: '3',
    name: 'دردشة طبية',
    description: 'تواصل مع طبيبك عبر الدردشة للحصول على استشارات سريعة',
    price: 25,
    duration: 15,
    category: 'الاستشارات',
    features: ['رد فوري', 'مشاركة الملفات', 'تاريخ المحادثات'],
    isPopular: false,
    icon: 'ChatBubbleLeftRightIcon',
  },
  {
    id: '4',
    name: 'الملف الطبي',
    description: 'احتفظ بملفك الطبي الكامل وتاريخك المرضي في مكان آمن',
    price: 0,
    duration: 0,
    category: 'السجلات',
    features: ['تشفير آمن', 'نسخ احتياطي', 'مشاركة مع الأطباء'],
    isPopular: false,
    icon: 'DocumentTextIcon',
  },
  {
    id: '5',
    name: 'مواعيد الطوارئ',
    description: 'احجز موعد طوارئ في أي وقت للحالات العاجلة',
    price: 100,
    duration: 60,
    category: 'الطوارئ',
    features: ['استجابة سريعة', 'أطباء متاحين 24/7', 'أولوية عالية'],
    isPopular: false,
    icon: 'ClockIcon',
  },
  {
    id: '6',
    name: 'أمان البيانات',
    description: 'بياناتك الطبية محمية بأعلى معايير الأمان والخصوصية',
    price: 0,
    duration: 0,
    category: 'الأمان',
    features: ['تشفير متقدم', 'امتثال GDPR', 'مراجعة أمنية'],
    isPopular: false,
    icon: 'ShieldCheckIcon',
  },
];
